/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f1edec',
        'surface-container-high': '#ebe7e7',
        'surface-container-highest': '#e5e2e1',
        'surface-variant': '#e5e2e1',
        'surface': '#fcf8f8',
        'surface-dim': '#ddd9d9',
        'surface-bright': '#fcf8f8',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#444748',
        'outline': '#747878',
        'outline-variant': '#c4c7c8',
        'secondary': '#425e91',
        'on-secondary': '#ffffff',
        'secondary-container': '#a8c4fe',
        'on-secondary-container': '#345083',
        'on-secondary-fixed': '#001a40',
        'on-secondary-fixed-variant': '#294678',
        'secondary-fixed': '#d7e2ff',
        'secondary-fixed-dim': '#acc7ff',
        'background': '#fcf8f8',
        'on-background': '#1c1b1b',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f4f0ef',
        'gold': '#D4AF37',
        'navy': '#001a40',
      },
      fontFamily: {
        'lexend': ['Lexend', 'sans-serif'],
        'work': ['Work Sans', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['72px', { lineHeight: '1.1', letterSpacing: '0.04em', fontWeight: '800' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
